import React from 'react'
import '../index.css'

function Footer(){
    return (
        <footer>
            <ul className="footer">
                <ul>Users generated by <a href="https://randomuser.me/">Random User Generator</a></ul>
            </ul>
        </footer>
    )
}

export default Footer